name: Upload Files to S3

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug GitHub Context
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Ref: ${{ github.ref }}"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::272795261907:role/GitHubActionsRole
          aws-region: us-east-1

      - name: Upload input files to S3
        run: |
          aws s3 cp data/input/ s3://aws-databricks-project-delete-2026/input/